// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsfeedAPI;

#nullable disable

namespace NewsfeedAPI.Migrations
{
    [DbContext(typeof(NewsfeedDbContext))]
    partial class NewsfeedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NewsfeedAPI.Entity.Newsfeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Newsfeeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Newsfeed Application, data from mysql",
                            Name = "Newsfeed API"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
